#%RAML 1.0
title: Hello world
version: v1
protocols: [ HTTP ]
mediaType: application/json

uses:
  proxy: lib/raml-proxy.raml

types:
  Hello:
    description: Hello response
    properties:
      message: string
      path: string

/helloworld:
  (proxy.ProxyPass): http://www.google.pt
  get:
    responses:
      200:
        body:
          application/json:
            type: Hello
  /{name}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Hello

/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Hello
              